Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  # Speed up downloads using a shared cache across boxes
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.boot_timeout = 1200

end
